export let LANG = {
    "fr" : {
        "main_title" : "Enseignement pour adultes et de formation continue",
        "inscriptions_btn" : "Inscriptions",
        "navbar_home" : "Accueil",
        "navbar_infos" : "Infos",
        "navbar_formations" : "Formations",
        "navbar_actus" : "Actualités",
        "fr_lang" : "Français",
        "en_lang" : "English",
        "search_btn" : "Rechercher",
        "index_actus_h2" : "Actualités",
        "index_actus_subtitle" : "Découvrez les évènements à venir",
        "index_actus_month" : "Avril",
        "index_actu_descr" : "Du 15 au 20 avril, venez découvrir nos salles de cours et nos divers programmes de formation lors de la Promsoc’Week !",
        "index_actu_detail_btn" : "Tous les détails",
        "index_actus_all_actus_btn" : "Toutes les actualités",
        "index_types_title" : "Types d'enseignement",
        "index_types_btn_01" : "01 Enseignement \n" + " supérieur",
        "index_types_btn_02" : "02 Enseignement\n" + " secondaire",
        "index_types_btn_03" : "03 Apprentissage\n" + " des langues",
        "index_types_all_formations_btn" : "Voir les formations",
        "index_formations_title" : "Nos formations",
        "index_formation_cat1" : "Formations animalières",
        "index_formation_cat2" : "Enseignement supérieur",
        "index_formation_cat3" : "Formations techniques et de l'artisanat",
        "index_formation_cat4" : "Administration tertiaire",
        "index_formation_cat5" : "Aide à la réussite",
        "index_formation_cat6" : "Bien-être et soin aux personnes",
        "index_formation_cat7" : "Langues et FLE",
        "index_formation_cat8" : "Orientation paramédical",
        "index_formation_night" : "Soir",
        "index_formation_day" : "Jour",
        "index_formation_day_night" : "Jour - Soir",
        "index_formation_year" : "an(s)",
        "index_formation_name_veto" : "Assistant(e) vétérinaire",
        "index_formation_name_canine" : "Esthétique canine",
        "index_formation_name_business" : "Bachelier e-business",
        "index_formation_name_electromeca" : "Bachelier en électromécanique",
        "index_formation_name_tech_infos" : "Technicien en informatique",
        "index_formation_name_antiquaire" : "Antiquaire et antiquaire spécialisation",
        "index_formation_name_agent_accueil" : "Agent en accueil et tourisme",
        "index_formation_name_complement_cess" : "Complément CESS",
        "index_formation_name_math_fr" : "Formation de base (Mathématique et français)",
        "index_formation_name_eao" : "EAO Niveau élémentaire et moyen - Word",
        "index_formation_name_dietetique" : "Approche des principes de base en diététique",
        "index_formation_name_estheticien" : "Esthéticien",
        "index_formation_name_anglais" : "Anglais",
        "index_formation_name_espagnol" : "Espagnol",
        "index_formation_name_dentaire" : "Agent d'accueil et de gestion d'un cabinet dentaire",
        "index_formation_name_aide_soignant" : "Aide soignant",
        "index_formation_btn" : "Plus d'infos",
        "index_formations_btn" : "Toutes nos formations",
        "index_formations_btn_here" : "ici",
        "footer_partenaires" : "Nos partenaires :",
        "footer_address" : "Ouvert du lundi au vendredi \n" + "de 8h30 à 12h00 et de 15h30 à 20h30 \n" + "Le samedi \n" + "de 8h30 à 13h30 \n" + "Fermé le dimanche",
        "footer_nav" : "Accès rapide",
        "footer_online" : "Plateforme en ligne :",
        "title_filtre" : "Filtrer",
        "filtre_cat" : "Catégories",
        "filtre_cours" : "Cours",
        "filtre_duree" : "Durée",
        "filtre_duree_1" : "Moins de 6mois",
        "filtre_duree_2" : "1 an",
        "filtre_duree_3" : "2 ans",
        "filtre_duree_4" : "3 ans",
        "filtre_duree_5" : "Plus de 3 ans",
        "contact_title" : "Contactez - nous",
        "contact_subtitle_1" : "Informations inscriptions",
        "contact_subtitle_2" : "Direction",
        "contact_subtitle_3" : "Informations techniques",
        "contact_subtitle_4" : "Plan et accès",
        "contact_card_title_1" : "Secrétariat",
        "contact_card_title_2" : "Directeur",
        "contact_card_title_3" : "Directrice adjointe",
        "contact_card_title_4" : "Directrice adjointe",
        "contact_card_title_5" : "Directeur adjoint",
        "contact_card_title_6" : "Secrétariat de direction",
        "contact_card_title_7" : "Comptable",
        "contact_card_title_8" : "Support informatique",
        "contact_map_title_1" : "Adresse",
        "contact_map_title_2" : "Heures d'ouverture",
        "formation_link_1" : "La formation",
        "formation_link_2" : "Conditions d'admission",
        "formation_link_3" : "Liste des cours",
        "formation_link_4" : "Débouchées",
        "formation_descr_title" : "Description complète",
        "formation_descr_lettrine" : "V",
        "formation_descr_content_1" : "ous aimez les animaux ? Vous ne demandez qu’à vous en occuper ? Votre rêve serait de commencer à travailler chez des vétérinaires ?",
        "formation_descr_content_2" : "Dans ce cas le cours d’assistant vétérinaire est un excellent choix !",
        "formation_descr_content_3" : "Un assistant vétérinaire assiste le vétérinaire d’une façon professionnelle. Il/elle veille à ce que tout y marche comme sur des roulettes. Il s’agit donc d’un travail varié ! Répondre professionnellement au téléphone, utilisation de l’outil informatique au service de la gestion des dossiers clients, du stock de médicaments, de matériel, d’accessoires, d’accueillir chaleureusement les clients, d’accompagner les propriétaires en leur offrant un soutien psychologique, de préparer les salles de consultation et de chirurgie, assister aux consultations, aux opérations/interventions chirurgicales, de surveiller les animaux hospitalisés, de conseiller les propriétaires d’animaux au niveau de l’alimentation, des comportements, des soins,...",
        "formation_descr_content_4" : "En contact direct avec la clientèle et les animaux, l’assistant vétérinaire travaille sous la responsabilité du vétérinaire. Il est le soutien du vétérinaire dans ses fonctions d’accueil des clients, de consultation, d’intervention, de gestion, de communication, de vente dans le respect des règles déontologiques et des dispositions légales applicables aux médecins vétérinaires.",
        "formation_cours_1" : "Activités liées à la pratique du vétérinaire",
        "formation_cours_2" : "Anatomie des animaux de compagnie",
        "formation_cours_3" : "Biologie des animaux de compagnie",
        "formation_cours_4" : "Eléments de bureautique",
        "formation_cours_5" : "Eléments de législation et déontologie appliqués au domaine vétérinaire",
        "formation_cours_6" : "Éthologie du chien et du chat",
        "formation_cours_7" : "Nutrition des animaux de compagnie",
        "formation_cours_8" : "Pathologie des animaux de compagnie",
        "formation_cours_9" : "Pharmacologie et toxicologie des animaux de compagnie",
        "formation_cours_10" : "Physiologie des animaux de compagnie",
        "formation_cours_11" : "Stage d’intégration de la section : assistant vétérinaire",
        "formation_cours_12" : "Stage d’observation de la section : assistant vétérinaire",
        "formation_cours_13" : "Systématique et extérieur",
        "formation_cours_14" : "Techniques approfondies de secrétariat",
        "formation_cours_15" : "Techniques d’accueil et d’organisation de bureau",
        "formation_cours_16" : "Épreuve intégrée de la section : assistant vétérinaire",
        "formation_debouchee_title" : "Liste des débouchés",
        "formation_debouchee_1" : "Cliniques vétérinaires",
        "formation_debouchee_2" : "Centres vétérinaires",
        "formation_debouchee_3" : "Cabinets vétérinaires",
        "formation_conditions_1" : "Etre titulaire du certificat d’enseignement secondaire inférieur (CESI ou C2D)",
        "or" : "OU",
        "formation_conditions_2" : "Présenter une épreuve écrite d’admission en français et mathématique de niveau secondaire inférieur.",
        "sidebar_menu_horaire" : "Horaire de jour",
        "sidebar_menu_duree" : "Durée",
        "sidebar_menu_titre" : "Titre délivré",
        "formation_questions_title" : "Des questions ?",
        "formation_questions_link" : "Contactez - nous",
        "formation_horaire_download" : "Horaire PDF",
        "sidebar_time_txt_1" : "Minimum 2 ans et demi à raison de 3 ou 4 soirées par semaine, de 17H45 à 21H05 et/ou samedi.",
        "sidebar_time_txt_2" : "La formation peut être échelonnée sur 2 1/2 à 5 ans en respectant l’organigramme de la section.",
        "sidebar_time_txt_3" : "Ce système modulaire permet un étalement des unités d’enseignement.",
        "sidebar_titredelivre_1" : "Attestation de réussite pour chaque unité d’enseignement. Certificat de qualification d’ASSISTANT VÉTÉRINAIRE spécifique à l'enseignement secondaire supérieur de promotion sociale. Ce diplôme est visé et reconnu par la Fédération Wallonie-Bruxelles.",
        "sidebar_titredelivre_2" : "Ce diplôme est visé et reconnu par la Fédération Wallonie-Bruxelles.",
        "actus_page_title" : "Actualités",
        "actus_page_modal_title" : "COURS OUVERT",
        "actus_page_modal_p2" : "Cette semaine de cours ouverts est une occasion idéale pour explorer la vie étudiante de notre établissement et prendre des décisions pour votre avenir, en envisageant vos futurs projets de manière concrète.",
        "actus_page_modal_p3" : "Tous nos cours seront accessibles, sauf en cas d’évaluation. Pour participer, il vous suffit de vous inscrire au secrétariat dès votre arrivée. Notre équipe se fera un plaisir de vous guider.",
        "actus_page_modal_p4" : "Pour connaître l’horaire des cours, RDV sur notre site Internet. Deux étapes :",
        "actus_page_modal_p5" : "L’équipe du secrétariat se tient aussi à votre disposition pour tout renseignement et précision.",
        "actus_page_modal_li1" : "Sélectionnez la section qui vous intéresse et téléchargez l’horaire correspondant.",
        "actus_page_modal_li2" : "Le jour de votre visite, avant de venir, consultez l’horaire du jour sur la page d’accueil de notre site.\n" +
            "https://www.namur-cadets.be/formations",
        "actus_page_modal_close" : "Fermer",
        "infos_page_accordion_title1" : "01 Conditions d'âge",
        "infos_page_accordion_title2" : "02 Droits et coûts d'inscription",
        "infos_page_accordion_title3" : "03 Exonération du droit d'inscription",
        "infos_page_accordion_title4" : "04 Modalités d’inscription",
        "infos_page_accordion_title5" : "05 Modalités de préinscription pour les ressortissants hors UE",
        "infos_page_accordion_title6" : "06 Informations / Documents supplémentaires",
        "infos_page_accordion_title7" : "07 Organisation des UE (Unités d'enseignement)",
        "infos_page_accordion_title8" : "08 Site d'Eghezée",
        "infos_page_accordion_title9" : "09 Calendrier scolaire",
        "infos_page_conditions_li1" : "Avoir au moins 15 ans et avoir suivi les deux premières années de l'enseignement secondaire.",
        "infos_page_conditions_li2" : "Avoir 16 ans et, jusqu'à la date anniversaire de ses 18 ans, l'étudiant doit fournir la preuve qu'il est inscrit dans l'enseignement de plein exercice ou dans l'enseignement à horaire réduit.",
        "infos_page_conditions_li3" : "Avoir 18 ans pour l'accès à l'enseignement supérieur (BAC, Graduat, BES, CAP). L'étudiant ne peut être inscrit à plus de 36 ECTS par année académique avant l'âge de 20 ans accomplis.",
        "infos_page_conditions_li4" : "Le titre de bachelier ne peut pas être délivré avant l'âge de 23 ans et le titre de BES avant l'âge de 22 ans.",
        "infos_page_conditions_li5" : "Satisfaire aux conditions d'admission prévues dans les dossiers pédagogiques (voir conditions générales d'admission pour chaque UE et/ou section-formation).",
        "infos_page_droit_partone_title1" : "Droit d'inscription (DI)",
        "infos_page_droit_partone_title2" : "Droit d'inscription complémentaires (DIC)",
        "infos_page_droit_partone_title3" : "Le coût total",
        "inofs_page_droit_txt1" : "Les étudiants paient (sauf exonération) un droit d'inscription dont le montant est calculé au prorata du nombre de périodes de cours (50 minutes) suivis et en fonction du niveau d'enseignement.",
        "inofs_page_droit_txt2" : "Secondaire : 32,00 € frais fixes + 0,28 € la période plafonné à 800 périodes.",
        "inofs_page_droit_txt3" : "Supérieur : 32,00 € frais fixes + 0,44 € la période plafonné à 800 périodes.",
        "inofs_page_droit_txt4" : "Minerval étranger est fixé à 30,00 € la période hebdomadaire plafonné à 238,00 € par année scolaire.",
        "inofs_page_droit_txt5" : "En addition du droit d'inscription les étudiants paient un droit d'inscription complémentaire (DIC) qui correspond aux frais administratifs fixés par l'établissement et qui se calcule comme suit:",
        "inofs_page_droit_txt6" : "Frais forfaitaires 25 € + 0.10 € la période avec un maximum de 55 € par année scolaire.",
        "inofs_page_droit_txt7" : "Le coût total payé par l'étudiant reprend donc le montant du droit d'inscription (DI) et celui du droit d'inscription complémentaire (DIC).",
        "inofs_page_droit_txt8" : "Le paiement de votre inscription se fera au secrétariat de préférence PAR BANCONTACT. Il est éventuellement possible d'étaler le coût de l'inscription dans une section, en ne s'inscrivant que dans les premières UE (attention, l'inscription dans les UE suivantes devra se faire au fur et à mesure de la progression dans le cursus).",
        "infos_page_exo_txt1" : "Le D.I.C. est payable par tous. Le droit d'inscription (DI) est payable par tous dès l'inscription et le remboursement des personnes exonérées se fera uniquement par virement bancaire sur le numéro de compte communiqué lors de l'inscription. Il pourront être exonéré du droit d'inscription (DI), moyennant la remise d'une attestation au plus tard du premier dixième de la formation, dans les cas suivants, une exonération du droit d'inscription principal est accordée :",
        "infos_page_exo_txt2" : "Les mineurs soumis à l'obligation scolaire ;",
        "infos_page_exo_txt3" : "Les chômeurs complets indemnisés, à l'exclusion :",
        "infos_page_exo_txt4" : "Des chômeurs en formation professionnelle bénéficiant d'un contrat de formation professionnelle individuelle en entreprise leur procurant des revenus supplémentaires ;",
        "infos_page_exo_txt5" : "Des chômeurs mis au travail et des prépensionnés ;",
        "infos_page_exo_txt6" : "Les demandeurs d'emploi inoccupés obligatoirement inscrits en vertu des réglementations relatives à l'emploi et au chômage, aux handicapés ou à l'aide sociale ;",
        "infos_page_exo_txt7" : "Les personnes en situation de handicap qui fournissent un document probant, c'est-à-dire toute preuve ou attestation délivrée par une administration publique compétente ou toute décision judiciaire reconnaissant un handicap, une invalidité, une maladie professionnelle, un accident de travail ou le droit commun ayant entraîné une incapacité permanente. Ces preuves et attestations sont établies par écrit ou sous toute autre forme imposée par l'organe chargé de les délivrer ;",
        "infos_page_exo_txt8" : "Les personnes qui bénéficient du revenu d'intégration sociale (RIS) ou d'une aide financière équivalente au revenu d'intégration sociale (ERIS) ;",
        "infos_page_exo_txt9" : "Les miliciens ;",
        "infos_page_exo_txt10" : "Les personnes soumises à une obligation imposée par une autorité publique ;",
        "infos_page_exo_txt11" : "Les membres su personnel directeur, enseignant, auxiliaires d'éducation et les membres du personnel administratif de l'enseignement organisé ou subventionné par la Fédération Wallonie-Bruxelles, pour lesquels la section, la formation ou l'unité de formation à laquelle ils s'inscrivent est reconnue dans le cadre de la formation en cours de carrière des membres du personnel enseignant ;",
        "infos_page_exo_txt12" : "Les membres du personnel de l'enseignement organisé ou subventionné par Fédération Wallonie-Bruxelles, pour lesquels la section, la formation ou l'unité de formation considérée constitue un recyclage dans le cadre de leur(s) fonction(s) dans l'enseignement.",
        "infos_page_exo_txt13" : "Les étudiants repris dans les catégories ci-dessus paient une inscription complémentaire: frais forfaitaires 20 € + 0.10 € la période avec un maximum de 50 € par année scolaire.",
        "infos_page_inscr_txt1" : "À l'inscription, pensez à prévoir les documents suivants :",
        "infos_page_inscr_txt2" : "Votre carte d’identité",
        "infos_page_inscr_txt3" : "Votre titre d’étude (voir fiche descriptive de la section)",
        "infos_page_inscr_txt4" : "Pour les demandeurs d’emploi : votre numéro d'inscription au FOREM",
        "infos_page_inscr_txt5" : "Pour les personnes émargeant au CPAS : l'attestation du CPAS, couvrant le premier dixième de la première unité d'enseignement dans laquelle s’inscrit l’étudiant",
        "infos_page_inscr_txt5/5" : "Votre attestation de l’AViQ pour les personnes reconnues",
        "infos_page_inscr_txt6" : "Documents supplémentaires pour les personnes ayant une carte d'identité de nationalité non-européenne:",
        "infos_page_inscr_txt7" : "Votre composition de ménage",
        "infos_page_inscr_txt8" : "Réfugié : attestation de l’organisme dépendant de l’office des étrangers ou du centre où ils sont hébergés",
        "infos_page_inscr_txt9" : "Si travail : contrat de travail",
        "infos_page_inscr_txt10" : "À charge (époux, parents, …) : contrat de travail ou attestation forem ou CPAS de la personne responsable",
        "infos_page_inscr_txt11" : "En recours : lettre de l’avocat datée du mois en cours",
        "infos_page_inscr_txt12" : "Pour les étudiants qui possèdent une CI limitée au 31/10, séjour limité aux études. Si le séjour est autorisé sur base du statut étudiant, l'étudiant doit répondre aux conditions suivantes pour obtenir son autorisation de séjour provisoire (ASP) ou le renouvellement de celle-ci:",
        "infos_page_inscr_txt13" : "S'inscrire dans l'enseignement supérieur (graduat/bachelier/master) pour l'année scolaire (40 semaines) dans un même cursus;",
        "infos_page_inscr_txt14" : "Fournir un extrait de registre national reprenant la date de la première arrivée en Belgique (document TI 006);",
        "infos_page_inscr_txt15" : "S'il vient d'un autre institut, apporter la preuve de son inscription pour chaque année académique (=annexe 3 (historique de ses études reprenant le nombre de crédits suivis et le nombre de crédits réussis) + preuves)",
        "infos_page_pre_txt1" : "L’inscription à l’EAFC Namur Cadets est établie conformément à la réglementation en vigueur dans l’enseignement de la Fédération Wallonie-Bruxelles et au règlement d’ordre intérieur (ROI) de l’établissement scolaire.",
        "infos_page_pre_txt2" : "Les préinscriptions sont ouvertes à concurrence de places disponibles.",
        "infos_page_pre_txt3" : "L’EAFC n’autorise pas un candidat à poursuivre ses études de manière excessive dans l’enseignement de promotion sociale (EPS). Le candidat doit respecter la circulaire 8681 relatives aux conditions d’accès à l’enseignement de promotion sociale pour les ressortissants d’un pays hors de l’Union européenne.",
        "infos_page_docsupp1" : "Congé - Education",
        "infos_page_docsupp2" : "Valorisation des acquis - dispense",
        "infos_page_docsupp3" : "L'enseignement supérieur en Promotion Sociale",
        "infos_page_docsupp4" : "Le glossaire de la Promotion Sociale",
        "infos_page_docsupp5" : "Règlement d'ordre intérieur",
        "infos_page_ue_txt1" : "L’EAFC Namur Cadets se réserve le droit, à tout moment, de ne pas organiser systématiquement toutes les UE et sections proposées sur le site.",
        "infos_page_ue_txt2" : "Cette décision peut avoir pour origine, par exemple un nombre insuffisant d’inscriptions dans une ou des UE et/ou section(s), une alternance programmée de certaines UE d’une année scolaire à l’autre, ou peut résulter d’une décision unilatérale de la Direction de l’école.",
        "infos_page_ue_txt3" : "En cas de non-organisation d’une UE dans laquelle des élèves seraient inscrits, ils seront bien entendu contactés par le secrétariat et verront leurs droits d’inscription intégralement remboursés.",
        "infos_page_eghezee_txt1" : "Certaines sections et/ou activités d'apprentissage notamment des sections géomètres, construction, esthétique canine, menuiserie et garnissage se donneront ou pourraient se donner sur le site de l'ITCF Henri Maus situé Chaussée de Louvain, 92 à 5310 Eghezée. Ces informations peuvent évoluer dans le temps. Renseignez-vous au secrétariat dès votre inscription dans ces sections.",
        "inofs_page_calendar_txt1" : "Lundi 26 août 2024",
        "inofs_page_calendar_txt2" : "Vendredi 27 septembre 2024",
        "inofs_page_calendar_txt3" : "Du lundi 21 octobre 2024 au dimanche 3 novembre 2024",
        "inofs_page_calendar_txt4" : "Lundi 11 novembre 2024",
        "inofs_page_calendar_txt5" : "Du samedi 21 décembre 2024 au dimanche 5 janvier 2025",
        "inofs_page_calendar_txt6" : "Du lundi 24 février 2025 au dimanche 9 mars 2025",
        "inofs_page_calendar_txt7" : "Lundi 21 avril 2025",
        "inofs_page_calendar_txt8" : "Du samedi 26 avril 2025 au dimanche 11 mai 2025",
        "inofs_page_calendar_txt9" : "Jeudi 29 mai 2025",
        "inofs_page_calendar_txt10" : "Lundi 9 juin 2025",
        "inofs_page_calendar_txt11" : "5 juillet 2025",
        "infos_page_calendar_title1" : "Rentrée scolaire",
        "infos_page_calendar_title2" : "Fête de la Communauté française",
        "infos_page_calendar_title3" : "Congé d'automne (Toussaint)",
        "infos_page_calendar_title4" : "Jour de l'Armistice",
        "infos_page_calendar_title5" : "Vacances d'hiver (Noël)",
        "infos_page_calendar_title6" : "Congé de détente (Carnaval)",
        "infos_page_calendar_title7" : "Lundi de Pâques",
        "infos_page_calendar_title8" : "Vacances de printemps (Pâques)",
        "infos_page_calendar_title9" : "Jeudi de l'Ascension",
        "infos_page_calendar_title10" : "Lundi de Pentecôte",
        "infos_page_calendar_title11" : "Vacances d'été",
    },
    "en" : {
        "main_title" : "Adults education and continuing education",
        "inscriptions_btn" : "Registration",
        "navbar_home" : "Home",
        "navbar_infos" : "Infos",
        "navbar_formations" : "Our training",
        "navbar_actus" : "News",
        "fr_lang" : "Français",
        "en_lang" : "English",
        "search_btn" : "Search",
        "index_actus_h2" : "News",
        "index_actus_subtitle" : "Discover our futur events",
        "index_actus_month" : "April",
        "index_actu_descr" : "From the 15 to the 20th of april, come and discover our classrooms and our diverse education program during the PromSoc Week !",
        "index_actu_detail_btn" : "All the details",
        "index_actus_all_actus_btn" : "All the news",
        "index_types_title" : "Education type",
        "index_types_btn_01" : "01 College\n" + " degree",
        "index_types_btn_02" : "02 Secondary\n" + " school education",
        "index_types_btn_03" : "03 Language\n" + " learning",
        "index_types_all_formations_btn" : "All training",
        "index_formations_title" : "Our training",
        "index_formation_cat1" : "Animal training",
        "index_formation_cat2" : "College degree",
        "index_formation_cat3" : "technical and craftsmanship training",
        "index_formation_cat4" : "Tertiary administration",
        "index_formation_cat5" : "Success aid",
        "index_formation_cat6" : "Well-being and personal care",
        "index_formation_cat7" : "Languages and FLE",
        "index_formation_cat8" : "Paramedic orientation",
        "index_formation_night" : "Evening",
        "index_formation_day" : "Daytime",
        "index_formation_day_night" : "Daytime - Evening",
        "index_formation_year" : "year(s)",
        "index_formation_name_veto" : "Veterinary Assistant",
        "index_formation_name_canine" : "Dog esthetics",
        "index_formation_name_business" : "Bachelor in e-business",
        "index_formation_name_electromeca" : "Bachelor in electromechanics",
        "index_formation_name_tech_infos" : "IT Technician",
        "index_formation_name_antiquaire" : "Antiquarian and antiquarian specialist",
        "index_formation_name_agent_accueil" : "Reception and tourism officer",
        "index_formation_name_complement_cess" : "Complementary CESS",
        "index_formation_name_math_fr" : "Basic training (Mathematics and french)",
        "index_formation_name_eao" : "EAO basic and medium level - Word",
        "index_formation_name_dietetique" : "Basic principles of dietetics",
        "index_formation_name_estheticien" : "Esthetician",
        "index_formation_name_anglais" : "English",
        "index_formation_name_espagnol" : "Spanish",
        "index_formation_name_dentaire" : "Dental office management and reception",
        "index_formation_name_aide_soignant" : "Caregiver",
        "index_formation_btn" : "More info",
        "index_formations_btn" : "All our training",
        "index_formations_btn_here" : "here",
        "footer_partenaires" : "Our partners :",
        "footer_address" : "Open Monday to Friday \n" + "de 8.30am à 12.00am and from 3.30pm à 8.30pm \n" + "On Saterday \n" + "from 8.30am to 1.30pm \n" + "Closed on Sunday",
        "footer_nav" : "Easy access",
        "footer_online" : "Online platform :",
        "title_filtre" : "Filter",
        "filtre_cat" : "Categories",
        "filtre_cours" : "Courses",
        "filtre_duree" : "Duration",
        "filtre_duree_1" : "Less than 6 months",
        "filtre_duree_2" : "1 year",
        "filtre_duree_3" : "2 years",
        "filtre_duree_4" : "3 years",
        "filtre_duree_5" : "More than 3 years",
        "contact_title" : "Contact us",
        "contact_subtitle_1" : "Registration information",
        "contact_subtitle_2" : "Direction",
        "contact_subtitle_3" : "Technical information",
        "contact_subtitle_4" : "Map and access",
        "contact_card_title_1" : "Secretariat",
        "contact_card_title_2" : "Director",
        "contact_card_title_3" : "Vice director",
        "contact_card_title_4" : "Vice director",
        "contact_card_title_5" : "Vice director",
        "contact_card_title_6" : "Management secretariat",
        "contact_card_title_7" : "Accountant",
        "contact_card_title_8" : "IT support",
        "contact_map_title_1" : "Address",
        "contact_map_title_2" : "Opening hours",
        "formation_link_1" : "The training",
        "formation_link_2" : "Admission requirement",
        "formation_link_3" : "Course roster",
        "formation_link_4" : "Job opportunities",
        "formation_descr_title" : "Full description",
        "formation_descr_lettrine" : "D",
        "formation_descr_content_1" : "o you love animals? Do you just want to look after them? Your dream would be to start working for vets ?",
        "formation_descr_content_2" : "Then the veterinary assistant course is an excellent choice!",
        "formation_descr_content_3" : "A veterinary assistant supports the vet in a professional way. He/she ensures that everything runs smoothly. So it's a varied job! Answering the telephone professionally, using IT tools to manage client files, stock of medicines, equipment and accessories, welcoming clients warmly, accompanying owners by offering them psychological support, preparing consultation and surgery rooms, attending consultations and operations/surgeries, supervising hospitalised animals, advising pet owners on diet, behaviour, care, etc.",
        "formation_descr_content_4" : "In regular contact with customers and animals, veterinary assistants work under the responsibility of the veterinary surgeon. They support the veterinary surgeon in his duties of receiving customers, consulting, intervening, managing, communicating and selling in compliance with the ethical rules and legal provisions applicable to veterinary surgeons.",
        "formation_cours_1" : "Activities related to veterinary practice",
        "formation_cours_2" : "Pet anatomy",
        "formation_cours_3" : "Pet biology",
        "formation_cours_4" : "Office automation",
        "formation_cours_5" : "Elements of legislation and ethics applied to the veterinary field",
        "formation_cours_6" : "Dog and cat ethology",
        "formation_cours_7" : "Pet nutrition",
        "formation_cours_8" : "Pet pathology",
        "formation_cours_9" : "Pet pharmacology and toxicology",
        "formation_cours_10" : "Pet physiology",
        "formation_cours_11" : "Section integration course: veterinary assistant",
        "formation_cours_12" : "Section observation course: veterinary assistant",
        "formation_cours_13" : "Systematic and external",
        "formation_cours_14" : "Advanced secretarial techniques",
        "formation_cours_15" : "Reception and office organization techniques",
        "formation_cours_16" : "Section integrated test: veterinary assistant",
        "formation_debouchee_title" : "Job opportunities",
        "formation_debouchee_1" : "Veterinary clinics",
        "formation_debouchee_2" : "Veterinary centers",
        "formation_debouchee_3" : "Veterinary practices",
        "formation_conditions_1" : "Hold a certificate of lower secondary education (CESI or C2D)",
        "or" : "OR",
        "formation_conditions_2" : "take a written admission test in French and lower secondary mathematics.",
        "sidebar_menu_horaire" : "Daytime schedule",
        "sidebar_menu_duree" : "Time",
        "sidebar_menu_titre" : "Title delivered",
        "formation_questions_title" : "Any questions ?",
        "formation_questions_link" : "Contact - us",
        "formation_horaire_download" : "Schedule PDF",
        "sidebar_time_txt_1" : "At least 2 and half years, with 3 or 4 evenings per week, from 5.45pm to 9.05pm and/or Saturdays.",
        "sidebar_time_txt_2" : "Training can be spread over 2 1/2 to 5 years, depending on the section's organisation chart.",
        "sidebar_time_txt_3" : "This modular system makes it possible to spread out the teaching units.",
        "sidebar_titredelivre_1" : "Certificate of accomplishment for each teaching unit. Certificate of qualification as a VETERINARY ASSISTANT dedicated to secondary education of social promotion.",
        "sidebar_titredelivre_2" : "This diploma is approved and recognised by the Wallonia-Brussels Federation.",
        "actus_page_title" : "News",
        "actus_page_modal_title" : "OPEN CLASS",
        "actus_page_modal_p2" : "This week of open courses is an ideal opportunity to explore student life at our school and make decisions for your future, by looking at your future projects in a concrete way.",
        "actus_page_modal_p3" : "All our courses will be accessible, except in the case of evaluation. To participate, simply register with the secretary's office on arrival. Our team will be happy to guide you.",
        "actus_page_modal_p4" : "To find out the course schedule, visit our website. Two steps :",
        "actus_page_modal_p5" : "The secretarial team is also at your disposal for any information and clarification you may require.",
        "actus_page_modal_li1" : "Select the section you are interested in and download the corresponding timetable.",
        "actus_page_modal_li2" : "On the day of your visit, before coming, check the daily schedule on the home page of our website.\n" +
            "https://www.namur-cadets.be/formations",
        "actus_page_modal_close" : "Close",
        "infos_page_accordion_title1" : "01 Age requirements",
        "infos_page_accordion_title2" : "02 Registration fees and costs",
        "infos_page_accordion_title3" : "03 Exemption from registration fee",
        "infos_page_accordion_title4" : "04 Terms of registration",
        "infos_page_accordion_title5" : "05 Pre-registration procedures for non-european union citizens",
        "infos_page_accordion_title6" : "06 Informations / Additional documents",
        "infos_page_accordion_title7" : "07 Organisation of units (UE)",
        "infos_page_accordion_title8" : "08 Eghezée site",
        "infos_page_accordion_title9" : "09 School calendar",
        "infos_page_conditions_li1" : "Must be at least 15 years old and have completed the first two years of secondary school.",
        "infos_page_conditions_li2" : "Students must be 16 years old and, until their 18th birthday, must provide proof of enrolment in full- or part-time education.",
        "infos_page_conditions_li3" : "Must be 18 for access to higher education (BAC, Graduat, BES, CAP). Students may not register for more than 36 ECTS per academic year before the age of 20.",
        "infos_page_conditions_li4" : "The bachelor's degree cannot be awarded before the age of 23, and the BES degree before the age of 22.",
        "infos_page_conditions_li5" : "Meet the admission requirements set out in the pedagogical files (see general admission requirements for each UE and/or training section).",
        "infos_page_droit_partone_title1" : "Registration fee (RF)",
        "infos_page_droit_partone_title2" : "Additional registration fee (ARF)",
        "infos_page_droit_partone_title3" : "Total cost",
        "inofs_page_droit_txt1" : "Students pay a registration fee (unless exempted), the amount of which is calculated in proportion to the number of class periods (50 minutes) attended and according to the level of instruction.",
        "inofs_page_droit_txt2" : "Secondary: €32.00 fixed fee + €0.28 per period, capped at 800 periods.",
        "inofs_page_droit_txt3" : "Higher education: €32.00 fixed fee + €0.44 per period, up to a maximum of 800 periods.",
        "inofs_page_droit_txt4" : "The minervalue for foreigners is set at €30.00 per weekly period, capped at €238.00 per school year.",
        "inofs_page_droit_txt5" : "In addition to the registration fee, students pay a complementary registration fee (ARF) which corresponds to the administrative costs set by the school and is calculated as follows: ",
        "inofs_page_droit_txt6" : "Fixed fee €25 + €0.10 per period with a maximum of €55 per school year.",
        "inofs_page_droit_txt7" : "The total cost paid by the student includes the registration fee (RF) and the complementary registration fee (ARF).",
        "inofs_page_droit_txt8" : "Payment of your registration must be made to the secretariat, preferably BY BANCONTACT. It may be possible to spread the cost of registration in a section over time, by enrolling only in the first UE (note that registration in subsequent UE must be made as you progress through the course).",
        "infos_page_exo_txt1" : "The A.R.F. is payable by all. The registration fee (R.F.) is payable by all upon registration, and those exempted will be refunded only by bank transfer to the account number provided at the time of registration. The registration fee may be waived in the following cases, subject to presentation of a certificate no later than the first tenth of the course, The main registration fee is waived for :",
        "infos_page_exo_txt2" : "Minors required to attend school ;",
        "infos_page_exo_txt3" : "Unemployed people receiving full benefits, excluding :",
        "infos_page_exo_txt4" : "Unemployed people undergoing professional training and benefiting from an individual professional training contract in a company providing them with additional income ;",
        "infos_page_exo_txt5" : "Unemployed people put to work and early retirees;",
        "infos_page_exo_txt6" : "Free jobseekers who must be registered under regulations relating to employment and unemployment, the disabled or social assistance ;",
        "infos_page_exo_txt7" : "People with disabilities who provide documentary evidence, so any proof or certificate issued by a competent public authority or any court decision recognising a disability, invalidity, professional illness, accident at work or common law that has resulted in permanent incapacity. These proofs and certificates must be in writing or in any other form required by the body responsible for issuing them ;",
        "infos_page_exo_txt8" : "People benefiting  from the social integration income (RIS) or financial assistance equivalent to the social integration income (ERIS) ;",
        "infos_page_exo_txt9" : "Militiamen ;",
        "infos_page_exo_txt10" : "Persons subject to an order imposed by a public authority ;",
        "infos_page_exo_txt11" : "Directors, teachers, teaching assistants and administrative staff in education organised or supported by the Wallonia-Brussels Federation, for whom the section, training course or training unit in which they enrol is recognised as part of the in-service training for teaching staff ;",
        "infos_page_exo_txt12" : "Members of teaching staff organised or supported by the Fédération Wallonie-Bruxelles, for whom the section, training course or training unit in question constitutes retraining in the context of their teaching function(s).",
        "infos_page_exo_txt13" : "Students in the above categories pay an additional registration fee of €20 + €0.10 per period up to a maximum of €50 per school year.",
        "infos_page_inscr_txt1" : "When you register, please bring the following documents with you :",
        "infos_page_inscr_txt2" : "Your identity card",
        "infos_page_inscr_txt3" : "Your study title (see section description)",
        "infos_page_inscr_txt4" : "For jobseekers: your FOREM registration number",
        "infos_page_inscr_txt5" : "For CPAS payers: the CPAS certificate covering the first tenth of the first course unit in which the student is enrolled",
        "infos_page_inscr_txt5/5" : "Your AViQ certificate for recognised persons",
        "infos_page_inscr_txt6" : "Additional documents for people with a non-European identity card :",
        "infos_page_inscr_txt7" : "Your household composition",
        "infos_page_inscr_txt8" : "Refugees: attestation from the organisation dependent on the foreign Office or the centre where they are accommodated",
        "infos_page_inscr_txt9" : "If employed: employment contract",
        "infos_page_inscr_txt10" : "Dependent (spouse, parents, etc.): employment contract or certificate from forem or CPAS of the person responsible",
        "infos_page_inscr_txt11" : "If appealing: letter from the lawyer dated the current month",
        "infos_page_inscr_txt12" : "For students with a CI limited to 31/10, residence limited to studies. If the residence is authorised on the basis of student status, the student must meet the following conditions in order to obtain a provisional residence permit (ASP) or its extension :",
        "infos_page_inscr_txt13" : "Enrol in higher education (degree/bachelor/master) for the school year (40 weeks) in the same course;",
        "infos_page_inscr_txt14" : "Provide an extract from the national register showing the date of first admission to Belgium (document TI 006);",
        "infos_page_inscr_txt15" : "If coming from another institute, provide proof of enrolment for each academic year (=Appendix 3 (history of studies including number of credits taken and number of credits passed) + proof).",
        "infos_page_pre_txt1" : "Registration at the EAFC Namur Cadets is established in accordance with the regulations in application in the education system of the Wallonia-Brussels Federation and the school's internal regulations (ROI).",
        "infos_page_pre_txt2" : "Pre-registration is open to the number of places available.",
        "infos_page_pre_txt3" : "The EAFC does not authorise a candidate to continue his/her studies excessively in social promotion education (EPS). Applicants must comply with circular 8681 on the conditions of access to social promotion education for nationals of countries outside the European Union.",
        "infos_page_docsupp1" : "Holiday - Education",
        "infos_page_docsupp2" : "Valorisation of previous skills - Exemption",
        "infos_page_docsupp3" : "Higher education in social promotion",
        "infos_page_docsupp4" : "Glossary of Social Promotion",
        "infos_page_docsupp5" : "Internal rules",
        "infos_page_ue_txt1" : "The EAFC Namur Cadets reserves the right, at any time, not to systematically organise all the courses and sections offered on the site. ",
        "infos_page_ue_txt2" : "This decision may be due, for example, to an insufficient number of registration in one or more UE and/or section(s), to the scheduled alternation of certain UE from one school year to the next, or may be the result of a unilateral decision by the school management. ",
        "infos_page_ue_txt3" : "If a UE in which students are enrolled is not organised, they will of course be contacted by the secretariat and their registration fees will be totally refunded.",
        "infos_page_eghezee_txt1" : "Some sections and/or learning activities, in particular the surveying, construction, canine esthetics, carpentry and upholstery sections, will or may be given at the ITCF Henri Maus site, Chaussée de Louvain 92, 5310 Eghezée. This information may change over time. Please contact the secretariat as soon as you register for these sections.",
        "inofs_page_calendar_txt1" : "Monday, August 26, 2024",
        "inofs_page_calendar_txt2" : "Friday, September 27, 2024",
        "inofs_page_calendar_txt3" : "Monday, October 21, 2024 to Sunday, November 3, 2024",
        "inofs_page_calendar_txt4" : "Monday, November 11, 2024",
        "inofs_page_calendar_txt5" : "From Saturday, December 21, 2024 to Sunday, January 5, 2025",
        "inofs_page_calendar_txt6" : "Monday, February 24, 2025 to Sunday, March 9, 2025",
        "inofs_page_calendar_txt7" : "Monday, April 21, 2025",
        "inofs_page_calendar_txt8" : "From Saturday April 26, 2025 to Sunday May 11, 2025",
        "inofs_page_calendar_txt9" : "Thursday, May 29, 2025",
        "inofs_page_calendar_txt10" : "Monday, June 9, 2025",
        "inofs_page_calendar_txt11" : "July 5, 2025",
        "infos_page_calendar_title1" : "Start of the school year",
        "infos_page_calendar_title2" : "French Community Day",
        "infos_page_calendar_title3" : "Autumn holiday (Toussaint)",
        "infos_page_calendar_title4" : "Armistice Day",
        "infos_page_calendar_title5" : "Winter holidays (Christmas)",
        "infos_page_calendar_title6" : "Relaxation vacation (Carnival)",
        "infos_page_calendar_title7" : "Easter Monday",
        "infos_page_calendar_title8" : "Spring holiday (Easter)",
        "infos_page_calendar_title9" : "Ascension Thursday",
        "infos_page_calendar_title10" : "Whitsun",
        "infos_page_calendar_title11" : "Summer vacation",
    }
}